name: CI/CD — Luiza AI Backend

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Black & Ruff
        run: |
          pip install --upgrade pip
          pip install black ruff

      - name: Run Ruff
        run: |
          ruff --verbose format

      - name: Check formatting with Black
        run: |
          black --check .

  build-and-publish:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/luiza-backend:latest
          secrets: |
            openai_api_key=${{ secrets.OPENAI_API_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_DEPLOY_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            set -e
            
            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/luiza-backend:latest
            
            # Stop & remove existing container
            docker stop luiza_assistant 2>/dev/null || true
            docker rm   luiza_assistant 2>/dev/null || true
            
            # Run new container with restart policy
            docker run -d \
              --name luiza_assistant \
              --restart unless-stopped \
              -p 8000:8000 \
              -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
              ${{ secrets.DOCKER_USERNAME }}/luiza-backend:latest
