# .github/workflows/ci-cd.yml
name: CI/CD — Luiza AI Assistant

on:
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with: python-version: '3.10'

      - name: Install deps & lint
        run: |
          pip install --upgrade pip
          pip install flake8
          flake8 .

      # (opcional) aqui você pode inserir testes unitários se tiver
      #- name: Run tests
      #  run: pytest --maxfail=1 --disable-warnings -q

  build-and-publish:
    runs-on: ubuntu-latest
    needs: lint-and-test
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/luiza-ai-assistant:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            set -e

            # 1) Puxe a última imagem
            docker pull ghcr.io/${{ github.repository_owner }}/luiza-ai-assistant:latest

            # 2) Pare e remova o container antigo
            docker stop luiza_assistant 2>/dev/null || true
            docker rm   luiza_assistant 2>/dev/null || true

            # 3) Rode novo container
            docker run -d \
              --name luiza_assistant \
              -p 8000:8000 \
              ghcr.io/${{ github.repository_owner }}/luiza-ai-assistant:latest
